FROM usgsastro/jenkins-worker:ubuntu-1804

ENV CONDA_HOME /home/jenkins/conda
ENV PATH $CONDA_HOME/bin:$PATH

USER root

RUN apt-get update && apt-get dist-upgrade -y
RUN apt-get install -y          \
    git                         \
    gcc                         \
    bzip2                       \
    ca-certificates             \
    x11-apps                    \
    libgl1-mesa-glx             \
    libglu1-mesa-dev

USER jenkins
WORKDIR /home/jenkins

RUN curl -s -o ~/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
RUN /bin/bash ~/miniconda.sh -b -p $CONDA_HOME
RUN rm ~/miniconda.sh

RUN conda config --prepend channels http://astro-bin.wr.usgs.gov/conda-usgs-astrogeology
RUN conda config --prepend channels http://astro-bin.wr.usgs.gov/conda-forge
RUN conda config --prepend channels http://astro-bin.wr.usgs.gov/conda

RUN conda update conda -y
